### ISSUE TITLE
Float division by zero in psm.logistic_ps

### ISSUE THREAD

**Issue by Luis-vllgh** [adriennekline/psmpy#1]
Hi there!

I am currently using PsmPy on a rather large dataset and I got the following error in the psm.logistic_ps command:

![image](https://user-images.githubusercontent.com/112629870/205668554-f9953871-9415-437a-8e93-9489fb360613.png)

This seems to occur during the calculation of the propensity_logit column. I dont think that one or many of the propensity scores are acutally equal to 1, but maybe the propensity score from the package is rounded at some stage of the algorithm? If I choose a slightly smaller dataset it runs and the highest propensity score ends up to be "0.9999986309511635". 

Do you have an idea how to fix this? Would help me out a lot! Thanks in advance

**Comment by adriennekline** [comment]
Hi Luis,

Which version are you using?

Thanks,
Adrienne

From: Luis Vollerigh ***@***.***>
Date: Monday, December 5, 2022 at 09:08
To: adriennekline/psmpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adriennekline/psmpy] Float division by zero in psm.logistic_ps (Issue #1)

Hi there!

I am currently using PsmPy on a rather large dataset and I got the following error in the psm.logistic_ps command:

[image]<https://user-images.githubusercontent.com/112629870/205668554-f9953871-9415-437a-8e93-9489fb360613.png>

This seems to occur during the calculation of the propensity_logit column. I dont think that one or many of the propensity scores are acutally equal to 1, but maybe the propensity score from the package is rounded at some stage of the algorithm? If I choose a slightly smaller dataset it runs and the highest propensity score ends up to be "0.9999986309511635".

Do you have an idea how to fix this? Would help me out a lot! Thanks in advance

**Comment by adriennekline** [comment]
I see the problem – I’ll have to make an update to the package. Will do so tonight and upload a new version and that should work just fine. Out of curiosity, how big is your dataset?

Adrienne


From: Luis Vollerigh ***@***.***>
Date: Monday, December 5, 2022 at 09:15
To: adriennekline/psmpy ***@***.***>
Cc: adriennekline ***@***.***>, Comment ***@***.***>
Subject: Re: [adriennekline/psmpy] Float division by zero in psm.logistic_ps (Issue #1)

Hi,

I am using PsmPy 0.3.6.

Best regards,
Luis

**Comment by Luis-vllgh** [comment]
Thanks for your fast response! That is great, I am looking forward to the update.

Right now I get the error at 750.000 rows, but that may be extended to >20 mio. rows

**Comment by adriennekline** [comment]
Ok. As you can probably guess, propensity score matching relies on a KNN.
And if you have > 20 million rows this will likely become incomputable (in
the second step i.e. matching).

**Comment by Luis-vllgh** [comment]
Thanks for the advice! I already have an idea how to work around this problem. Will see if it works..

**Comment by Luis-vllgh** [comment]
I'll let you know! :)

**Comment by Luis-vllgh** [comment]
Hi Adrienne, it works perfectly fine! Thanks for the update to the package :)
