### ISSUE TITLE
Change dependency from "sklearn" to "scikit-learn"

### ISSUE THREAD

**Issue by hatcherdw** [adriennekline/psmpy#3]
Hi Adrienne,

Can you please change the "sklearn" dependency to "scikit-learn"? The scikit-learn maintainers are deprecating that spelling of the package name. See this page for more information: https://github.com/scikit-learn/sklearn-pypi-package.

Thanks,
Daniel

**Comment by adriennekline** [comment]
Hi Daniel,

This has now been taken care of, thanks for bringing it to my attention.

Adrienne

**Comment by hatcherdw** [comment]
I can see the dependency name in change psmpy version 0.3.9. Thanks Adrienne.
